name: FACL
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
  - mordred-descriptor
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=3_kmp_llvm
  - aiohappyeyeballs=2.4.4=py39h06a4308_0
  - aiohttp=3.11.10=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - async-timeout=5.0.1=py39h06a4308_0
  - attrs=24.3.0=py39h06a4308_0
  - biopython=1.85=py39hb25bd0a_0
  - blas=1.0=mkl
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=1.17.1=py39h15c3d72_0
  - cftime=1.6.4=py39h5eee18b_0
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.4.127=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-version=11.8=h70ddcb2_3
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.18=hb2f20db_0
  - deepchem=2.8.0=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - expat=2.7.0=h5888daf_0
  - fasteners=0.20=py39h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py39h9399b63_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - frozenlist=1.5.0=py39h5eee18b_0
  - future=1.0.0=pyhd8ed1ab_2
  - gds-tools=1.9.1.3=0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=h6a678d5_0
  - gnutls=3.6.15=he1e5248_0
  - greenlet=3.2.3=py39hf88036b_0
  - griddataformats=1.0.2=pyhd8ed1ab_1
  - gsd=4.0.0=py39h8cd3c5a_0
  - h5py=3.14.0=py39he0d80d8_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.14.5=h2b7332f_2
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - icu=70.1=h27087fc_0
  - idna=3.7=py39h06a4308_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.6=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.15.0=hc1efc7f_0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnetcdf=4.8.1=hebfe86d_5
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.9=h87c4ccc_0
  - libprotobuf=3.21.12=hfc55251_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzip=1.8.0=h6ac8c49_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightning-utilities=0.14.3=pyhd8ed1ab_0
  - llvm-openmp=20.1.2=h024ca30_1
  - lmdb=0.9.31=hd590300_1
  - magma=2.6.2=hc72dce7_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdanalysis=2.7.0=py39hddac248_1
  - mkl=2022.2.1=h6508926_16999
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mordred=1.2.0=pyhe5148d4_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py39hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - mrcfile=1.5.4=pyhd8ed1ab_0
  - msgpack-python=1.1.1=py39h6a678d5_0
  - multidict=6.1.0=py39h5eee18b_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nccl=2.26.2.1=h03a54cd_1
  - ncurses=6.4=h6a678d5_0
  - netcdf4=1.7.2=py39h25c56f8_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - ninja=1.12.1=h297d8ca_0
  - nsight-compute=2024.1.1.4=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.26.4=py39h474f0d3_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.3.0=py39h3b40f6f_0
  - pcre2=10.43=hcad00b1_0
  - pillow=11.1.0=py39hac6e08b_1
  - pip=25.0=py39h06a4308_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.7=pyh29332c3_0
  - propcache=0.3.1=py39h5eee18b_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pycairo=1.25.0=py39hc92de75_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-core=2.33.1=py39h3506688_0
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-lmdb=1.6.2=py39hcca4d6b_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytng=0.3.1=py39h1f09d53_2
  - pytorch=1.13.1=cuda112py39hb0b7ed5_200
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-lightning=2.2.5=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h5eee18b_0
  - reportlab=4.4.1=py39h8cd3c5a_0
  - requests=2.32.3=py39h06a4308_1
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=py39h06a4308_3
  - sentry-sdk=2.26.1=pyhd8ed1ab_0
  - setproctitle=1.3.5=py39h8cd3c5a_0
  - setuptools=75.8.0=py39h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlalchemy=2.0.41=py39h8cd3c5a_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.9.0=hf52228f_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tidynamics=1.1.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - torch-geometric=2.6.1=pyhd8ed1ab_0
  - torch-scatter=2.1.1=py39h17475c7_0
  - torchaudio=0.13.1=py39_cu116
  - torchmetrics=1.5.2=pyhd8ed1ab_1
  - torchvision=0.14.1=py39_cu116
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wandb=0.19.9=py39h43652db_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - wheel=0.45.1=py39h06a4308_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.18.0=py39h5eee18b_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==0.33.0
      - aiobotocore==2.24.1
      - aioitertools==0.12.0
      - alembic==1.16.5
      - anndata==0.10.9
      - array-api-compat==1.11.2
      - asttokens==3.0.0
      - beautifulsoup4==4.13.5
      - botocore==1.39.11
      - cellxgene-census==1.15.0
      - colorlog==6.10.1
      - comm==0.2.3
      - dataclasses==0.6
      - datasets==2.19.2
      - decorator==5.2.1
      - dill==0.3.8
      - et-xmlfile==2.0.0
      - evaluate==0.4.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.19.1
      - fsspec==2024.3.1
      - fuzzywuzzy==0.18.0
      - get-annotations==0.1.2
      - gget==0.29.2
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jmespath==1.0.1
      - jupyterlab-widgets==3.0.15
      - legacy-api-wrap==1.4.1
      - llvmlite==0.43.0
      - lxml==6.0.1
      - mako==1.3.10
      - matplotlib-inline==0.1.7
      - multiprocess==0.70.16
      - mysql-connector-python==9.4.0
      - natsort==8.4.0
      - numba==0.60.0
      - openpyxl==3.1.5
      - optuna==4.6.0
      - parso==0.8.5
      - patsy==1.0.1
      - pexpect==4.9.0
      - prompt-toolkit==3.0.51
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pytdc==1.1.15
      - rdkit==2023.9.6
      - regex==2025.7.34
      - s3fs==2024.3.1
      - safetensors==0.6.2
      - scanpy==1.10.3
      - session-info==1.0.1
      - somacore==1.0.11
      - soupsieve==2.7
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - stdlib-list==0.11.1
      - tiledb==0.29.1
      - tiledbsoma==1.11.4
      - tokenizers==0.21.4
      - tomli==2.3.0
      - torchtext==0.4.0
      - traitlets==5.14.3
      - transformers==4.50.3
      - umap-learn==0.5.9.post2
      - urllib3==1.26.20
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xxhash==3.5.0
